import { Document, Image, Page, StyleSheet, Text, View } from "@react-pdf/renderer";

import type { AnalysisResult, AnalyzeRequest } from "./types";

const styles = StyleSheet.create({
  page: {
    padding: 34,
    fontFamily: "Helvetica",
    color: "#111827",
    backgroundColor: "#ffffff"
  },
  header: {
    backgroundColor: "#070b18",
    color: "#ffffff",
    padding: 18,
    borderRadius: 10,
    marginBottom: 18
  },
  logo: {
    width: 130,
    height: 44,
    objectFit: "contain",
    marginBottom: 10
  },
  eyebrow: {
    fontSize: 8,
    letterSpacing: 1.4,
    color: "#67e8f9",
    textTransform: "uppercase",
    marginBottom: 6
  },
  title: {
    fontSize: 22,
    fontWeight: 700,
    marginBottom: 8
  },
  subtitle: {
    fontSize: 10,
    color: "#cbd5e1",
    lineHeight: 1.5
  },
  row: {
    flexDirection: "row",
    marginBottom: 12
  },
  col: {
    flex: 1,
    marginRight: 10
  },
  card: {
    border: "1 solid #e5e7eb",
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    backgroundColor: "#f8fafc"
  },
  darkCard: {
    backgroundColor: "#111827",
    color: "#ffffff",
    borderRadius: 8,
    padding: 12,
    marginBottom: 12
  },
  sectionTitle: {
    fontSize: 10,
    textTransform: "uppercase",
    letterSpacing: 1,
    color: "#475569",
    marginBottom: 7,
    fontWeight: 700
  },
  label: {
    fontSize: 8,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    color: "#64748b",
    marginBottom: 3
  },
  text: {
    fontSize: 10,
    lineHeight: 1.5,
    marginBottom: 4
  },
  small: {
    fontSize: 8,
    color: "#64748b",
    lineHeight: 1.4
  },
  score: {
    fontSize: 34,
    fontWeight: 700,
    color: "#22d3ee"
  },
  footer: {
    marginTop: 18,
    paddingTop: 10,
    borderTop: "1 solid #e5e7eb",
    fontSize: 8,
    color: "#64748b",
    textAlign: "center"
  }
});

function ListText({ items }: { items: string[] }) {
  return (
    <View>
      {(items.length ? items : ["None"]).map((item) => (
        <Text key={item} style={styles.text}>- {item}</Text>
      ))}
    </View>
  );
}

export function BrandReportDocument({ result, request }: { result: AnalysisResult; request: AnalyzeRequest }) {
  const generatedDate = request.client_details.date_generated || new Date().toLocaleDateString();

  return (
    <Document title="EverVFX AI Brand Content Analysis Report">
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Image src="/evervfx-logo.png" style={styles.logo} />
          <Text style={styles.eyebrow}>EverVFX AI Brand Content Analyzer</Text>
          <Text style={styles.title}>Brand Content Analysis Report</Text>
          <Text style={styles.subtitle}>Generated by EverVFX AI Brand Content Analyzer on {generatedDate}</Text>
        </View>

        <View style={styles.row}>
          <View style={styles.darkCard}>
            <Text style={styles.label}>Overall score</Text>
            <Text style={styles.score}>{result.overall_score}/100</Text>
            <Text style={styles.text}>{result.score_label} - {result.publish_readiness}</Text>
          </View>
          <View style={styles.card}>
            <Text style={styles.sectionTitle}>Client Details</Text>
            <Text style={styles.text}>Client: {request.client_details.client_name || request.brand}</Text>
            <Text style={styles.text}>Campaign: {request.client_details.campaign_name || request.campaign_goal}</Text>
            <Text style={styles.text}>Prepared by: {request.client_details.prepared_by || "EverVFX"}</Text>
            <Text style={styles.text}>Brand manager: {request.client_details.brand_manager_name || "Not specified"}</Text>
          </View>
        </View>

        <View style={styles.card}>
          <Text style={styles.sectionTitle}>Project Context</Text>
          <Text style={styles.text}>Brand: {request.brand}</Text>
          <Text style={styles.text}>Platform: {request.platform}</Text>
          <Text style={styles.text}>Post type: {request.post_type}</Text>
          <Text style={styles.text}>Campaign goal: {request.campaign_goal}</Text>
          <Text style={styles.text}>Audience: {request.audience || "Not specified"}</Text>
        </View>

        <View style={styles.card}>
          <Text style={styles.sectionTitle}>Original Caption</Text>
          <Text style={styles.text}>{request.caption}</Text>
        </View>

        <View style={styles.card}>
          <Text style={styles.sectionTitle}>Score Summary</Text>
          {Object.entries(result.score_breakdown).map(([label, item]) => (
            <Text key={label} style={styles.text}>{label}: {item.score}/{item.max_score}</Text>
          ))}
        </View>

        <View style={styles.card}>
          <Text style={styles.sectionTitle}>Detailed Analysis</Text>
          <Text style={styles.text}>Hook: {result.hook_analysis.hook_strength} ({result.hook_analysis.hook_score}/10). {result.hook_analysis.comment}</Text>
          <Text style={styles.text}>Tone: {result.tone_analysis.detected_tone.join(", ")} ({result.tone_analysis.tone_score}/15). {result.tone_analysis.comment}</Text>
          <Text style={styles.text}>CTA: {result.cta_analysis.detected_cta || "Not detected"} ({result.cta_analysis.cta_strength}/15). {result.cta_analysis.comment}</Text>
          <Text style={styles.text}>Hashtags: {result.hashtag_analysis.hashtag_count} hashtags ({result.hashtag_analysis.hashtag_score}/5). {result.hashtag_analysis.comment}</Text>
          <Text style={styles.text}>Caption quality: {result.caption_quality.clarity_score}/15. {result.caption_quality.comment}</Text>
        </View>
      </Page>

      <Page size="A4" style={styles.page}>
        <View style={styles.card}>
          <Text style={styles.sectionTitle}>Problems Found</Text>
          <ListText items={result.problems} />
        </View>

        <View style={styles.card}>
          <Text style={styles.sectionTitle}>Suggestions</Text>
          <ListText items={result.suggestions} />
        </View>

        <View style={styles.darkCard}>
          <Text style={styles.sectionTitle}>Improved Caption</Text>
          <Text style={styles.text}>{result.improved_caption}</Text>
        </View>

        <View style={styles.card}>
          <Text style={styles.sectionTitle}>Campaign Brief</Text>
          <Text style={styles.text}>Angle: {result.campaign_brief.content_angle}</Text>
          <Text style={styles.text}>Tone: {result.campaign_brief.caption_tone}</Text>
          <Text style={styles.text}>CTA: {result.campaign_brief.recommended_cta}</Text>
          <Text style={styles.text}>Key message: {result.campaign_brief.key_message}</Text>
          <Text style={styles.text}>Follow-up: {result.campaign_brief.suggested_follow_up_content}</Text>
        </View>

        <View style={styles.card}>
          <Text style={styles.sectionTitle}>Design Direction</Text>
          <Text style={styles.text}>Visual style: {result.design_direction.visual_style}</Text>
          <Text style={styles.text}>Colors: {result.design_direction.colors.join(", ")}</Text>
          <Text style={styles.text}>Typography: {result.design_direction.typography}</Text>
          <Text style={styles.text}>Layout: {result.design_direction.layout_suggestion}</Text>
          <Text style={styles.text}>Imagery: {result.design_direction.imagery_suggestion}</Text>
        </View>

        <View style={styles.card}>
          <Text style={styles.sectionTitle}>Calendar Suggestion</Text>
          <Text style={styles.text}>Suggested day: {result.calendar_suggestion.suggested_day}</Text>
          <Text style={styles.text}>Content role: {result.calendar_suggestion.content_role}</Text>
          <ListText items={result.calendar_suggestion.weekly_sequence} />
        </View>

        {result.competitor_comparison.available ? (
          <View style={styles.card}>
            <Text style={styles.sectionTitle}>Competitor Comparison</Text>
            <Text style={styles.text}>{result.competitor_comparison.summary}</Text>
            <Text style={styles.text}>Recommendation: {result.competitor_comparison.recommendation}</Text>
          </View>
        ) : null}

        <View style={styles.card}>
          <Text style={styles.sectionTitle}>Final Recommendation</Text>
          <Text style={styles.text}>{result.final_recommendation}</Text>
          {request.client_details.report_notes ? <Text style={styles.small}>Notes: {request.client_details.report_notes}</Text> : null}
        </View>

        <Text style={styles.footer}>Generated by EverVFX AI Brand Content Analyzer</Text>
      </Page>
    </Document>
  );
}

